# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
FastAPI application for HouseholdBasketEnv.

Standard endpoints (auto-generated by openenv.core.env_server.http_server):
    POST /reset, POST /step, GET /state, GET /schema, WS /ws

Custom endpoint:
    GET /tasks  -> task definitions for the agent runner
"""

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv-core is required. Install with: pip install 'openenv-core[core]>=0.2.1'"
    ) from e

try:
    from ..models import BasketAction, BasketObservation
    from .environment import HouseholdBasketEnvironment
except ImportError:  # pragma: no cover - support running from inside server/ folder
    from models import BasketAction, BasketObservation
    from server.environment import HouseholdBasketEnvironment


app = create_app(
    HouseholdBasketEnvironment,
    BasketAction,
    BasketObservation,
    env_name="household_basket_env",
    max_concurrent_envs=4,
)


TASK_DEFINITIONS = [
    {
        "id": "household_basket_task1",
        "name": "Single Healthy Adult Basket",
        "difficulty": "easy",
        "description": (
            "1 healthy adult, 3 valid steps, 20 curated products, 500 INR. "
            "Held-out easy eval — used as a regression check."
        ),
        "max_steps": 3,
        "score_range": [-3.0, 2.0],
        "reset_params": {"task_id": 1},
    },
    {
        "id": "household_basket_task2",
        "name": "Healthy + Diabetic Basket",
        "difficulty": "medium",
        "description": (
            "2 members (healthy adult + diabetic adult), 5 valid steps, 50 products, 1000 INR. "
            "Primary training tier (70% of training mix)."
        ),
        "max_steps": 5,
        "score_range": [-4.0, 3.0],
        "reset_params": {"task_id": 2},
    },
    {
        "id": "household_basket_task3",
        "name": "Diabetic + Hypertensive + Child Basket (adversarial)",
        "difficulty": "hard",
        "description": (
            "3 members (diabetic adult + hypertensive senior + growing child), 7 valid steps, "
            "492 products including 32 adversarial, 1500 INR. "
            "Headline tier — held-out seeds form the eval number."
        ),
        "max_steps": 7,
        "score_range": [-5.0, 4.0],
        "reset_params": {"task_id": 3},
    },
]


@app.get("/tasks", tags=["Tasks"])
async def list_tasks():
    return {"tasks": TASK_DEFINITIONS}


def main(host: str = "0.0.0.0", port: int = 8000) -> None:
    """Entry point for direct execution.

    Usage:
        uvicorn household_basket_env.server.app:app --host 0.0.0.0 --port 8000
        python -m household_basket_env.server.app
    """
    import uvicorn

    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    main()
